### ISSUE TITLE
Syntax Error at line 405

### ISSUE THREAD

**Issue by iminderN** [google/play-work#18]
I am getting a syntax error at line 405 (print json.dumps

**Comment by SimonJWin** [comment]
My guess is that you are using python 3, is that right?  

This script was written for python 2. It should be fairly straightforward to modify the script to work with python 2 and 3, so I will aim to do this. In the meantime, you should be able to run the script successfully with python 2.

Thanks!

**Comment by iminderN** [comment]
Yes that was the issue thanks

**Comment by hdurer** [comment]
We should keep this open and fix the script so it works with both Python 2 and 3.
