### ISSUE TITLE
minSDK was being treated as the targetSDK

### ISSUE THREAD

**Issue by dbskarl** [google/play-work#26]
We had a generated json file with minimum_sdk attribute set to 21 but after uploading it to google play store, we are getting warnings  **"Your app currently targets API level 21 and must target at least API level 26"**

**App Details**
minSDK: **21**
targetSDK: **27**
compiledSDK: **27**

We should not be getting this error as our targetSDK was already set to 27 (verified with apk analyzer as well). I can also observe that the generated json don't have a target_sdk attribute, is that expected?

**Comment by tommed** [comment]
+1

**Comment by tommed** [comment]
This is needed for all externally hosted APKs now that Google have introduced the requirement of the target SDK being higher than or equal to 26.

**Comment by faoustin** [comment]
Thank you for reporting, we are working on fixing the script.

**Comment by hdurer** [comment]
It seems that it's ok to just lie about the min_sdk; I tried that and it allowed me to publish the apk (which has a lower min_sdk) as long as the json file claims to be at least api 26.

Please have a look and re-open if this does not work for you.

**Comment by hdurer** [comment]
Ack, you are right.  We rolled back the change and are looking what needs to be done.  Currently the json format doesn't even allow specifying a `target_sdk` version.

**Comment by tommed** [comment]
Eeeek! Ok sounds like a bigger change; Sounds like we're slightly ahead of the curve of everyone else noticing this; hopefully the fix isn't too taxing. Thanks for looking into this.

**Comment by dbskarl** [comment]
> Ack, you are right. We rolled back the change and are looking what needs to be done. Currently the json format doesn't even allow specifying a `target_sdk` version.

Yes, same error is still there. Appreciate if you can provide some update on this. We are closely tracking this as we have a planned release this week. Hope it can be fix asap. Thanks

**Comment by hdurer** [comment]
> Yes, same error is still there. Appreciate if you can provide some update on this. We are closely tracking this as we have a planned release this week. Hope it can be fix asap. Thanks

My apologies for the slow response here.  I had added code to bypass the check last week but failed to be able to test it in internal systems before going on vacation for a few days.

That change has now been pushed to prod, and for my test account I managed to upload a json file with `minimum_sdk = 21` so I am hopeful that this is fixed.  Please try again and let us know if you still have problems.

**Comment by dbskarl** [comment]
> > Yes, same error is still there. Appreciate if you can provide some update on this. We are closely tracking this as we have a planned release this week. Hope it can be fix asap. Thanks
> 
> My apologies for the slow response here. I had added code to bypass the check last week but failed to be able to test it in internal systems before going on vacation for a few days.
> 
> That change has now been pushed to prod, and for my test account I managed to upload a json file with `minimum_sdk = 21` so I am hopeful that this is fixed. Please try again and let us know if you still have problems.

Thanks! This is fixed. I'm closing this issue.
