### ISSUE TITLE
Repeat: minSDK was being treated as the targetSDK

### ISSUE THREAD

**Issue by Jssmb** [google/play-work#30]
There appears to be a recurrence of #26 

On August 1, 2019 the minimum targetedSdk for new applications submitted [must be 28](https://developer.android.com/distribute/best-practices/develop/target-sdk).
When submitting the json file we have the following error:
"Your app currently targets API level 19 and must target at least API level 28 to ensure it is build on the latest APIs optimized for security and performance"

**App details:**
minSDK: **19**
targetSDK: **28**
compileSDK: **28**

@hdurer Is the same fix required again?

**Comment by hdurer** [comment]
It shouldn't have happened again since the validation was meant to be bypassed once and for all.

Give me a few days to find the right contact and see how we can fix this.

**Comment by hdurer** [comment]
Just double-checking: you *have* provided a non-empty url in there, right?

**Comment by Jssmb** [comment]
Yes, a (non-empty) url is included.

**Comment by hdurer** [comment]
Sorry, I cannot reproduce this.
I just tried this with a test account and a json file that declared `"minimum_sdk": "14"` and that was accepted without any problems.

The responsible person confirms that no new validation checks were added, so this should be working as before.

If you want me to investigate further and to avoid posting excessive private details here, drop me an email at `hdurer` `@google.com` with the json file you are trying to upload (omit the non-relevant details like cert, icon, file hashes etc. and change the url if you want to keep it private.  
Also, please include your developer id from the Play Console.  
Thanks.

**Comment by hdurer** [comment]
I believe Jssmb resolved this issue?

**Comment by Jssmb** [comment]
My apologies @hdurer for not closing the loop on this.

Yes this is resolved. It was something else in the console preventing the deployment.  The minSDK error just lead us down the wrong path.
Ideally that error should be removed when uploading the json file, but it does not block deployment
